# NOTE: This iaas is not currently tested by the cf-mysql team

properties:
  template_only:
    openstack:
      security_groups1: REPLACE_WITH_SG_LIST_1 # e.g. ["cf"]
      security_groups2: REPLACE_WITH_SG_LIST_2
      security_groups3: REPLACE_WITH_SG_LIST_3
      subnet_ids:
        mysql1: REPLACE_WITH_YOUR_SUBNET_ID_1
        mysql2: REPLACE_WITH_YOUR_SUBNET_ID_2
        mysql3: REPLACE_WITH_YOUR_SUBNET_ID_3

iaas_settings:
  <<: (( merge || nil ))

# NOTE:
# Replace 10.0.{0,1,2} part of the octet
# with your network configuration
  subnet_configs:
  - name: mysql1
    type: manual
    subnets:
    - range: 10.10.32.0/24
      reserved:
        - 10.10.32.2 - 10.10.32.9
        - 10.10.32.130 - 10.10.32.254
      static:
        - 10.10.32.10 - 10.10.32.14
      gateway: 10.10.32.1
      dns:
        - REPLACE_WITH_YOUR_DNS_SERVER
      cloud_properties:
        net_id: (( properties.template_only.openstack.subnet_ids.mysql1 ))
        security_groups: (( properties.template_only.openstack.security_groups1 ))
  - name: mysql2
    type: manual
    subnets:
    - range: 10.10.33.0/24
      reserved:
        - 10.10.33.2 - 10.10.33.9
        - 10.10.33.130 - 10.10.33.254
      static:
        - 10.10.33.10 - 10.10.33.14
      gateway: 10.10.33.1
      dns:
        - REPLACE_WITH_YOUR_DNS_SERVER
      cloud_properties:
        net_id: (( properties.template_only.openstack.subnet_ids.mysql2 ))
        security_groups: (( properties.template_only.openstack.security_groups2 ))
  - name: mysql3
    type: manual
    subnets:
    - range: 10.10.34.0/24
      reserved:
        - 10.10.34.2 - 10.10.34.9
        - 10.10.34.130 - 10.10.34.254
      static:
        - 10.10.34.10 - 10.10.34.14
      gateway: 10.10.34.1
      dns:
        - REPLACE_WITH_YOUR_DNS_SERVER
      cloud_properties:
        net_id: (( properties.template_only.openstack.subnet_ids.mysql3 ))
        security_groups: (( properties.template_only.openstack.security_groups3 ))

  stemcell: &stemcell
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent
    version: latest
  compilation_cloud_properties:
    instance_type: m1.medium
  resource_pool_cloud_properties:
  - name: mysql_z1
    cloud_properties:
      instance_type: m1.large

  - name: mysql_z2
    cloud_properties:
      instance_type: m1.large

  - name: mysql_z3
    cloud_properties:
      instance_type: m1.large

  - name: arbitrator_z3
    cloud_properties:
      instance_type: m1.small

  - name: proxy_z1
    cloud_properties:
      instance_type: m1.medium

  - name: proxy_z2
    cloud_properties:
      instance_type: m1.medium

  - name: cf-mysql-broker_z1
    cloud_properties:
      instance_type: m1.medium

  - name: cf-mysql-broker_z2
    cloud_properties:
      instance_type: m1.medium

  - name: errands_z1
    cloud_properties:
      instance_type: m1.medium

  disk_pools:
  - name: mysql-persistent-disk
    disk_size: 100000
