properties:
  vsphere:
    datacenters:
    - name: z1
      datacenter_name: REPLACE_WITH_YOUR_FIRST_DATACENTER
      clusters:
      - REPLACE_WITH_YOUR_FIRST_CLUSTER:
          resource_pool: REPLACE_WITH_YOUR_FIRST_RESOURCE_POOL
    - name: z2
      datacenter_name: REPLACE_WITH_YOUR_SECOND_DATACENTER
      clusters:
      - REPLACE_WITH_YOUR_SECOND_CLUSTER:
          resource_pool: REPLACE_WITH_YOUR_SECOND_RESOURCE_POOL
    - name: z3
      datacenter_name: REPLACE_WITH_YOUR_THIRD_DATACENTER
      clusters:
      - REPLACE_WITH_YOUR_THIRD_CLUSTER:
          resource_pool: REPLACE_WITH_YOUR_THIRD_RESOURCE_POOL
    subnet_names:
      mysql1: REPLACE_WITH_YOUR_SUBNET_NAME_1 #This should match your vSphere network name, e.g. "VM Network".
      mysql2: REPLACE_WITH_YOUR_SUBNET_NAME_2
      mysql3: REPLACE_WITH_YOUR_SUBNET_NAME_3

iaas_settings:
  <<: (( merge || nil ))

# NOTE:
# Replace 10.0.{0,1,2} part of the octet
# with your network configuration
  subnet_configs:
  - name: mysql1
    subnets:
    - range: 10.0.0.0/24
      gateway: 10.0.0.1
      reserved:
      - 10.0.0.2-10.0.0.109
      - 10.0.0.130-10.0.0.254
      static:
        - 10.0.0.120-10.0.0.124
      dns:
      - 10.0.0.3
      - 8.8.8.8
      cloud_properties:
        name: (( properties.vsphere.subnet_names.mysql1 ))
  - name: mysql2
    subnets:
    - range: 10.0.1.0/24
      gateway: 10.0.1.1
      reserved:
      - 10.0.1.2-10.0.1.109
      - 10.0.1.130-10.0.1.254
      static:
        - 10.0.1.120-10.0.1.124
      dns:
      - 10.0.1.3
      - 8.8.8.8
      cloud_properties:
        name: (( properties.vsphere.subnet_names.mysql2 ))
  - name: mysql3
    subnets:
    - range: 10.0.2.0/24
      gateway: 10.0.2.1
      reserved:
      - 10.0.2.2-10.0.2.109
      - 10.0.2.130-10.0.2.254
      static:
        - 10.0.2.120-10.0.2.124
      dns:
      - 10.0.2.3
      - 8.8.8.8
      cloud_properties:
        name: (( properties.vsphere.subnet_names.mysql3 ))

  stemcell: &stemcell
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
    version: latest
  compilation_workers: 4 # When setting this parameter, it overrides the default number of compilation workers (default=4)
  compilation_cloud_properties:
    ram: 4096
    disk: 20480
    cpu: 4
    datacenters:
    - name: (( .properties.vsphere.datacenters.z1.datacenter_name ))
      clusters: (( .properties.vsphere.datacenters.z1.clusters ))
  resource_pool_cloud_properties:
  - name: mysql_z1
    cloud_properties:
      ram: 4096
      disk: 10480
      cpu: 2
      datacenters:
      - name: (( .properties.vsphere.datacenters.z1.datacenter_name ))
        clusters: (( .properties.vsphere.datacenters.z1.clusters ))

  - name: mysql_z2
    cloud_properties:
      ram: (( iaas_settings.resource_pool_cloud_properties.mysql_z1.cloud_properties.ram ))
      disk: (( iaas_settings.resource_pool_cloud_properties.mysql_z1.cloud_properties.disk ))
      cpu: (( iaas_settings.resource_pool_cloud_properties.mysql_z1.cloud_properties.cpu ))
      datacenters:
      - name: (( .properties.vsphere.datacenters.z2.datacenter_name ))
        clusters: (( .properties.vsphere.datacenters.z2.clusters ))

  - name: mysql_z3
    cloud_properties:
      ram: (( iaas_settings.resource_pool_cloud_properties.mysql_z1.cloud_properties.ram ))
      disk: (( iaas_settings.resource_pool_cloud_properties.mysql_z1.cloud_properties.disk ))
      cpu: (( iaas_settings.resource_pool_cloud_properties.mysql_z1.cloud_properties.cpu ))
      datacenters:
      - name: (( .properties.vsphere.datacenters.z3.datacenter_name ))
        clusters: (( .properties.vsphere.datacenters.z3.clusters ))

  - name: arbitrator_z3
    cloud_properties:
      ram: 2048
      disk: 4096
      cpu: 1
      datacenters:
      - name: (( .properties.vsphere.datacenters.z3.datacenter_name ))
        clusters: (( .properties.vsphere.datacenters.z3.clusters ))

  - name: proxy_z1
    cloud_properties:
      ram: 2048
      disk: 4096
      cpu: 2
      datacenters:
      - name: (( .properties.vsphere.datacenters.z1.datacenter_name ))
        clusters: (( .properties.vsphere.datacenters.z1.clusters ))

  - name: proxy_z2
    cloud_properties:
      ram: (( iaas_settings.resource_pool_cloud_properties.proxy_z1.cloud_properties.ram ))
      disk: (( iaas_settings.resource_pool_cloud_properties.proxy_z1.cloud_properties.disk ))
      cpu: (( iaas_settings.resource_pool_cloud_properties.proxy_z1.cloud_properties.cpu ))
      datacenters:
      - name: (( .properties.vsphere.datacenters.z2.datacenter_name ))
        clusters: (( .properties.vsphere.datacenters.z2.clusters ))

  - name: cf-mysql-broker_z1
    cloud_properties:
      ram: 2048
      disk: 4096
      cpu: 1
      datacenters:
      - name: (( .properties.vsphere.datacenters.z1.datacenter_name ))
        clusters: (( .properties.vsphere.datacenters.z1.clusters ))

  - name: cf-mysql-broker_z2
    cloud_properties:
      ram: (( iaas_settings.resource_pool_cloud_properties.cf-mysql-broker_z1.cloud_properties.ram ))
      disk: (( iaas_settings.resource_pool_cloud_properties.cf-mysql-broker_z1.cloud_properties.disk ))
      cpu: (( iaas_settings.resource_pool_cloud_properties.cf-mysql-broker_z1.cloud_properties.cpu ))
      datacenters:
      - name: (( .properties.vsphere.datacenters.z2.datacenter_name ))
        clusters: (( .properties.vsphere.datacenters.z2.clusters ))

  - name: errands_z1
    cloud_properties:
      ram: 2048
      disk: 4096
      cpu: 1
      datacenters:
      - name: (( .properties.vsphere.datacenters.z1.datacenter_name ))
        clusters: (( .properties.vsphere.datacenters.z1.clusters ))

  disk_pools:
  - name: mysql-persistent-disk
    disk_size: 100000
