iaas_settings:

  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

  compilation_cloud_properties: {}

  watch_time: 10000-120000

  resource_pool_cloud_properties:
  - name: mysql_z1
    cloud_properties: {}
  - name: mysql_z2
    cloud_properties: {}
  - name: mysql_z3
    cloud_properties: {}
  - name: arbitrator_z3
    cloud_properties: {}
  - name: proxy_z1
    cloud_properties: {}
  - name: proxy_z2
    cloud_properties: {}
  - name: cf-mysql-broker_z1
    cloud_properties: {}
  - name: cf-mysql-broker_z2
    cloud_properties: {}
  - name: errands_z1
    cloud_properties: {}

  disk_pools:
  - name: mysql-persistent-disk
    disk_size: 100000
    cloud_properties: {}

  subnet_configs:
  - name: mysql1
    subnets:
    - cloud_properties:
        name: random
      range: 10.244.7.0/24
      reserved:
      - 10.244.7.1
      static:
      - 10.244.7.2
      - 10.244.7.3

  - name: mysql2
    subnets:
    - cloud_properties:
        name: random
      range: 10.244.8.0/24
      reserved:
      - 10.244.8.1
      static:
      - 10.244.8.2
      - 10.244.8.3

  - name: mysql3
    subnets:
    - cloud_properties:
        name: random
      range: 10.244.9.0/24
      reserved:
      - 10.244.9.1
      static:
      - 10.244.9.2
      - 10.244.9.6
